### ISSUE TITLE
Slow comparisons

### ISSUE THREAD

**Issue by FezVrasta** [lost-pixel/lost-pixel#401]
### Bug description

Hi, we are using the GitHub actions image with storybook, each screenshot comparison takes approximately 2 seconds, isn't that way too slow?

### How to reproduce

1. Use lost-pixel github action
2. Build storybook
3. Observe the comparisons logs
4. See it takes approximately 2 seconds for each comparison

**Comment by d-ivashchuk** [comment]
Are you running lost pixel in oss way or on our platform? can you share the logs please of your process from start to finish 🙏

**Comment by FezVrasta** [comment]
Thanks, we are using the open source solution. These are the logs.

https://gist.github.com/FezVrasta/cda78d55862e7f1987aec710719493fd

**Comment by d-ivashchuk** [comment]
just to make sure I got it right - from your logs & timestamps you can extrapolate that checking differences took more than 1.7 seconds?

We separate the process a bit so that might be a source of confusion - before checking the differences we need to make screenshots first, that is a costly operation, it is done on your CI machine so speed is really depending on that but overall I could guess it could take a second or two to create those images. 

Actual comparison step is usually super fast as we are using odiff as compare algo, for averagely sized storybook images(components) it shall take no more than couple of seconds, definitely not minutes.

@FezVrasta can you please confirm that we are talking about the same thing, e.g. that **_comparsion_** steps takes longer, not the step of taking actual screenshots?

**Comment by FezVrasta** [comment]
Thanks for the clarification, indeed the time was spent on the screenshots capture, we were running the storybook tests already in a previous step and I thought the screenshots generated there would be reused by lost pixel.

**Comment by d-ivashchuk** [comment]
you can use custom mode if screenshots are generated in previous step! it would limit some storybook specific features but overall will cut some time from your CI!
